{% set version = "2.0.0" %}

package:
  name: djangorestframework-yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-yaml/djangorestframework-yaml-{{ version }}.tar.gz
  sha256: 1b2cfd7482425f3c6924a8eb803d6f73276e76b03293cd7144c755753e029f15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.5
    - pip
    - pyyaml >=3.10

  run:
    - python >=3.5
    - pyyaml >=3.10

test:
  imports:
    - rest_framework_yaml
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/jpadilla/django-rest-framework-yaml
  license: BSD-3-Clause
  license_file: LICENSE
  summary: YAML support for Django REST Framework

extra:
  recipe-maintainers:
    - ocefpaf
