{% set version = "2.0.0" %}

package:
  name: djangorestframework-yaml
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/djangorestframework-yaml/djangorestframework-yaml-{{ version }}.tar.gz
  sha256: 1b2cfd7482425f3c6924a8eb803d6f73276e76b03293cd7144c755753e029f15

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pyyaml >=3.10

  run:
    - python
    - pyyaml >=3.10

test:
  imports:
    - rest_framework_yaml

about:
  home: https://github.com/jpadilla/django-rest-framework-yaml
  license: ISC
  # license_file: LICENSE not in the tarball
  summary: YAML support for Django REST Framework

extra:
  recipe-maintainers:
    - ocefpaf
