travis:
  secure:
    BINSTAR_TOKEN: d0m/cfRHUTchHSTHJAaZo2iOGqnIM+71xowRPidNuh7977NS9rGxSUi1sxqwHcpG6BKtXE4/WJkNypINhjwIhRSWx3nd/VN4spOnpPqS/NN91z7sUMHP3UIsvhnXtmzd8JBH27yu1Ux3abHNqTB7vvUFwt0vEVA56lHJkpAOZsPx93iU4dckXzQuSI8zdWW8GWvfmQftcxpO5jqU09ClS/yq8xIV9qcBC0FEQRq6kPmBeYeD4IkBrdSi3QB3FSQAy38pdKEF6wyR4ZeSNmY0+RWNk+eiifJXNRrWFhYkUk1k6X7WXV0nrVsUgo3DJfNFc43SMik8DjnOryQqRyBKFUpNsMRE2lzo4mx+xhgDmM+4SDX6MMPRm1iqRhz4AnTiTKDUg9FCw+BDu+jBmyWBglVM2pXgFTQujSUy3BMng9rrVxrMvZ+IHloCSb/Y8JWOvstulgRu7HuUHA/RA1XVcyUcxNChiGXap23aC75yA6aOt/6BbwZIOz0G9EwH9KTEAcL0sT8iTYl5Q82Ws3JTCnthKpGK4N7qa4+3dfTS3W8CFpyJe8YESD1R7DsnLVrPaVi6ipDA45kzfn2Lujj5LbBP72hg5VcLPjHETObaafbNXIlgwSH29jFrQii9d4Qs5hT6z4IgVnefD7Wj1em4i9iCnwD8EDcABrl8Gz9wwnE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
